<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
            array('id' => 1, 'currency_symbol' => '؋', 'currency_code' => 'AFN', 'code' => 'AF' ,'name' => "Afghanistan",'phonecode' => 93),
            array('id' => 2, 'currency_symbol' => 'Lek', 'currency_code' => 'ALL', 'code' => 'AL' ,'name' => "Albania",'phonecode' => 355),
            array('id' => 3, 'currency_symbol' => 'د.ج', 'currency_code' => 'DZD', 'code' => 'DZ' ,'name' => "Algeria",'phonecode' => 213),
            array('id' => 4, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'AS' ,'name' => "American Samoa",'phonecode' => 1684),
            array('id' => 5, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'AD' ,'name' => "Andorra",'phonecode' => 376),
            array('id' => 6, 'currency_symbol' => 'Kz', 'currency_code' => 'AOA', 'code' => 'AO' ,'name' => "Angola",'phonecode' => 244),
            array('id' => 7, 'currency_symbol' => '$', 'currency_code' => 'XCD', 'code' => 'AI' ,'name' => "Anguilla",'phonecode' => 1264),
            array('id' => 8, 'currency_symbol' => '$', 'currency_code' => 'XCD', 'code' => 'AQ' ,'name' => "Antarctica",'phonecode' => 0),
            array('id' => 9, 'currency_symbol' => '$', 'currency_code' => 'XCD', 'code' => 'AG' ,'name' => "Antigua And Barbuda",'phonecode' => 1268),
            array('id' => 10, 'currency_symbol' => '$', 'currency_code' => 'ARS', 'code' => 'AR','name' => "Argentina",'phonecode' => 54),
            array('id' => 11, 'currency_symbol' => 'Դ', 'currency_code' => 'AMD', 'code' => 'AM','name' => "Armenia",'phonecode' => 374),
            array('id' => 12, 'currency_symbol' => 'ƒ', 'currency_code' => 'AWG', 'code' => 'AW','name' => "Aruba",'phonecode' => 297),
            array('id' => 13, 'currency_symbol' => '$', 'currency_code' => 'AUD', 'code' => 'AU','name' => "Australia",'phonecode' => 61),
            array('id' => 14, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'AT','name' => "Austria",'phonecode' => 43),
            array('id' => 15, 'currency_symbol' => 'ман', 'currency_code' => 'AZN', 'code' => 'AZ','name' => "Azerbaijan",'phonecode' => 994),
            array('id' => 16, 'currency_symbol' => '$', 'currency_code' => 'BSD', 'code' => 'BS','name' => "Bahamas The",'phonecode' => 1242),
            array('id' => 17, 'currency_symbol' => 'ب.د', 'currency_code' => 'BHD', 'code' => 'BH','name' => "Bahrain",'phonecode' => 973),
            array('id' => 18, 'currency_symbol' => '৳', 'currency_code' => 'BDT', 'code' => 'BD','name' => "Bangladesh",'phonecode' => 880),
            array('id' => 19, 'currency_symbol' => '$', 'currency_code' => 'BBD', 'code' => 'BB','name' => "Barbados",'phonecode' => 1246),
            array('id' => 20, 'currency_symbol' => 'p.', 'currency_code' => 'BYR', 'code' => 'BY','name' => "Belarus",'phonecode' => 375),
            array('id' => 21, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'BE','name' => "Belgium",'phonecode' => 32),
            array('id' => 22, 'currency_symbol' => 'BZ$', 'currency_code' => 'BZD', 'code' => 'BZ','name' => "Belize",'phonecode' => 501),
            array('id' => 23, 'currency_symbol' => 'CFA', 'currency_code' => 'XOF', 'code' => 'BJ','name' => "Benin",'phonecode' => 229),
            array('id' => 24, 'currency_symbol' => '$', 'currency_code' => 'BMD', 'code' => 'BM','name' => "Bermuda",'phonecode' => 1441),
            array('id' => 25, 'currency_symbol' => '₹', 'currency_code' => 'INR', 'code' => 'BT','name' => "Bhutan",'phonecode' => 975),
            array('id' => 26, 'currency_symbol' => '$b', 'currency_code' => 'BOB', 'code' => 'BO','name' => "Bolivia",'phonecode' => 591),
            array('id' => 27, 'currency_symbol' => 'KM', 'currency_code' => 'BAM', 'code' => 'BA','name' => "Bosnia and Herzegovina",'phonecode' => 387),
            array('id' => 28, 'currency_symbol' => 'P', 'currency_code' => 'BWP', 'code' => 'BW','name' => "Botswana",'phonecode' => 267),
            array('id' => 29, 'currency_symbol' => 'kr', 'currency_code' => 'NOK', 'code' => 'BV','name' => "Bouvet Island",'phonecode' => 0),
            array('id' => 30, 'currency_symbol' => 'R$', 'currency_code' => 'BRL', 'code' => 'BR','name' => "Brazil",'phonecode' => 55),
            array('id' => 31, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'IO','name' => "British Indian Ocean Territory",'phonecode' => 246),
            array('id' => 32, 'currency_symbol' => '$', 'currency_code' => 'BND', 'code' => 'BN','name' => "Brunei",'phonecode' => 673),
            array('id' => 33, 'currency_symbol' => 'лв', 'currency_code' => 'BGN', 'code' => 'BG','name' => "Bulgaria",'phonecode' => 359),
            array('id' => 34, 'currency_symbol' => 'CFA', 'currency_code' => 'XOF', 'code' => 'BF','name' => "Burkina Faso",'phonecode' => 226),
            array('id' => 35, 'currency_symbol' => '₣', 'currency_code' => 'BIF', 'code' => 'BI','name' => "Burundi",'phonecode' => 257),
            array('id' => 36, 'currency_symbol' => '៛', 'currency_code' => 'KHR', 'code' => 'KH','name' => "Cambodia",'phonecode' => 855),
            array('id' => 37, 'currency_symbol' => '₣', 'currency_code' => 'XAF', 'code' => 'CM','name' => "Cameroon",'phonecode' => 237),
            array('id' => 38, 'currency_symbol' => '$', 'currency_code' => 'CAD', 'code' => 'CA','name' => "Canada",'phonecode' => 1),
            array('id' => 39, 'currency_symbol' => '$', 'currency_code' => 'CVE', 'code' => 'CV','name' => "Cape Verde",'phonecode' => 238),
            array('id' => 40, 'currency_symbol' => '$', 'currency_code' => 'KYD', 'code' => 'KY','name' => "Cayman Islands",'phonecode' => 1345),
            array('id' => 41, 'currency_symbol' => '₣', 'currency_code' => 'XAF', 'code' => 'CF','name' => "Central African Republic",'phonecode' => 236),
            array('id' => 42, 'currency_symbol' => '₣', 'currency_code' => 'XAF', 'code' => 'TD','name' => "Chad",'phonecode' => 235),
            array('id' => 43, 'currency_symbol' => '$', 'currency_code' => 'CLP', 'code' => 'CL','name' => "Chile",'phonecode' => 56),
            array('id' => 44, 'currency_symbol' => '¥', 'currency_code' => 'CNY', 'code' => 'CN','name' => "China",'phonecode' => 86),
            array('id' => 45, 'currency_symbol' => '$', 'currency_code' => 'AUD', 'code' => 'CX','name' => "Christmas Island",'phonecode' => 61),
            array('id' => 46, 'currency_symbol' => '$', 'currency_code' => 'AUD', 'code' => 'CC','name' => "Cocos (Keeling) Islands",'phonecode' => 672),
            array('id' => 47, 'currency_symbol' => '$', 'currency_code' => 'COP', 'code' => 'CO','name' => "Colombia",'phonecode' => 57),
            array('id' => 48, 'currency_symbol' => 'CF', 'currency_code' => 'KMF', 'code' => 'KM','name' => "Comoros",'phonecode' => 269),
            array('id' => 49, 'currency_symbol' => '₣', 'currency_code' => 'XAF', 'code' => 'CG','name' => "Congo",'phonecode' => 242),
            array('id' => 50, 'currency_symbol' => '', 'currency_code' => '', 'code' => 'CD','name' => "Congo The Democratic Republic Of The",'phonecode' => 242),
            array('id' => 51, 'currency_symbol' => '$', 'currency_code' => 'NZD', 'code' => 'CK','name' => "Cook Islands",'phonecode' => 682),
            array('id' => 52, 'currency_symbol' => '₡', 'currency_code' => 'CRC', 'code' => 'CR','name' => "Costa Rica",'phonecode' => 506),
            array('id' => 53, 'currency_symbol' => 'CFA', 'currency_code' => 'XOF', 'code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'phonecode' => 225),
            array('id' => 54, 'currency_symbol' => 'kn', 'currency_code' => 'HRK', 'code' => 'HR','name' => "Croatia (Hrvatska)",'phonecode' => 385),
            array('id' => 55, 'currency_symbol' => '₱', 'currency_code' => 'CUP', 'code' => 'CU','name' => "Cuba",'phonecode' => 53),
            array('id' => 56, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'CY','name' => "Cyprus",'phonecode' => 357),
            array('id' => 57, 'currency_symbol' => 'Kč', 'currency_code' => 'CZK', 'code' => 'CZ','name' => "Czech Republic",'phonecode' => 420),
            array('id' => 58, 'currency_symbol' => 'kr', 'currency_code' => 'DKK', 'code' => 'DK','name' => "Denmark",'phonecode' => 45),
            array('id' => 59, 'currency_symbol' => '₣', 'currency_code' => 'DJF', 'code' => 'DJ','name' => "Djibouti",'phonecode' => 253),
            array('id' => 60, 'currency_symbol' => '$', 'currency_code' => 'XCD', 'code' => 'DM','name' => "Dominica",'phonecode' => 1767),
            array('id' => 61, 'currency_symbol' => 'RD$', 'currency_code' => 'DOP', 'code' => 'DO','name' => "Dominican Republic",'phonecode' => 1809),
            array('id' => 62, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'TP','name' => "East Timor",'phonecode' => 670),
            array('id' => 63, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'EC','name' => "Ecuador",'phonecode' => 593),
            array('id' => 64, 'currency_symbol' => '£', 'currency_code' => 'EGP', 'code' => 'EG','name' => "Egypt",'phonecode' => 20),
            array('id' => 65, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'SV','name' => "El Salvador",'phonecode' => 503),
            array('id' => 66, 'currency_symbol' => '₣', 'currency_code' => 'XAF', 'code' => 'GQ','name' => "Equatorial Guinea",'phonecode' => 240),
            array('id' => 67, 'currency_symbol' => 'Nfk', 'currency_code' => 'ERN', 'code' => 'ER','name' => "Eritrea",'phonecode' => 291),
            array('id' => 68, 'currency_symbol' => '£', 'currency_code' => 'EUR', 'code' => 'EE','name' => "Estonia",'phonecode' => 372),
            array('id' => 69, 'currency_symbol' => 'Br', 'currency_code' => 'ETB', 'code' => 'ET','name' => "Ethiopia",'phonecode' => 251),
            array('id' => 70, 'currency_symbol' => '$', 'currency_code' => 'AUD', 'code' => 'XA','name' => "External Territories of Australia",'phonecode' => 61),
            array('id' => 71, 'currency_symbol' => '£', 'currency_code' => 'FKP', 'code' => 'FK','name' => "Falkland Islands",'phonecode' => 500),
            array('id' => 72, 'currency_symbol' => 'kr', 'currency_code' => 'DKK', 'code' => 'FO','name' => "Faroe Islands",'phonecode' => 298),
            array('id' => 73, 'currency_symbol' => '$', 'currency_code' => 'FJD', 'code' => 'FJ','name' => "Fiji Islands",'phonecode' => 679),
            array('id' => 74, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'FI','name' => "Finland",'phonecode' => 358),
            array('id' => 75, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'FR','name' => "France",'phonecode' => 33),
            array('id' => 76, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'GF','name' => "French Guiana",'phonecode' => 594),
            array('id' => 77, 'currency_symbol' => '₣', 'currency_code' => 'XPF', 'code' => 'PF','name' => "French Polynesia",'phonecode' => 689),
            array('id' => 78, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'TF','name' => "French Southern Territories",'phonecode' => 0),
            array('id' => 79, 'currency_symbol' => '₣', 'currency_code' => 'XPF', 'code' => 'GA','name' => "Gabon",'phonecode' => 241),
            array('id' => 80, 'currency_symbol' => 'D', 'currency_code' => 'GMD', 'code' => 'GM','name' => "Gambia The",'phonecode' => 220),
            array('id' => 81, 'currency_symbol' => 'ლ', 'currency_code' => 'GEL', 'code' => 'GE','name' => "Georgia",'phonecode' => 995),
            array('id' => 82, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'DE','name' => "Germany",'phonecode' => 49),
            array('id' => 83, 'currency_symbol' => '₵', 'currency_code' => 'GHS', 'code' => 'GH','name' => "Ghana",'phonecode' => 233),
            array('id' => 84, 'currency_symbol' => '£', 'currency_code' => 'GIP', 'code' => 'GI','name' => "Gibraltar",'phonecode' => 350),
            array('id' => 85, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'GR','name' => "Greece",'phonecode' => 30),
            array('id' => 86, 'currency_symbol' => 'kr', 'currency_code' => 'DKK', 'code' => 'GL','name' => "Greenland",'phonecode' => 299),
            array('id' => 87, 'currency_symbol' => '$', 'currency_code' => 'XCD', 'code' => 'GD','name' => "Grenada",'phonecode' => 1473),
            array('id' => 88, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'GP','name' => "Guadeloupe",'phonecode' => 590),
            array('id' => 89, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'GU','name' => "Guam",'phonecode' => 1671),
            array('id' => 90, 'currency_symbol' => 'Q', 'currency_code' => 'GTQ', 'code' => 'GT','name' => "Guatemala",'phonecode' => 502),
            array('id' => 91, 'currency_symbol' => '£', 'currency_code' => 'GBP', 'code' => 'XU','name' => "Guernsey and Alderney",'phonecode' => 44),
            array('id' => 92, 'currency_symbol' => '₣', 'currency_code' => 'GNF', 'code' => 'GN','name' => "Guinea",'phonecode' => 224),
            array('id' => 93, 'currency_symbol' => 'CFA', 'currency_code' => 'XOF', 'code' => 'GW','name' => "Guinea-Bissau",'phonecode' => 245),
            array('id' => 94, 'currency_symbol' => '$', 'currency_code' => 'GYD', 'code' => 'GY','name' => "Guyana",'phonecode' => 592),
            array('id' => 95, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'HT','name' => "Haiti",'phonecode' => 509),
            array('id' => 96, 'currency_symbol' => '$', 'currency_code' => 'AUD', 'code' => 'HM','name' => "Heard and McDonald Islands",'phonecode' => 0),
            array('id' => 97, 'currency_symbol' => 'L', 'currency_code' => 'HNL', 'code' => 'HN','name' => "Honduras",'phonecode' => 504),
            array('id' => 98, 'currency_symbol' => '$', 'currency_code' => 'HKD', 'code' => 'HK','name' => "Hong Kong S.A.R.",'phonecode' => 852),
            array('id' => 99, 'currency_symbol' => 'Ft', 'currency_code' => 'HUF', 'code' => 'HU','name' => "Hungary",'phonecode' => 36),
            array('id' => 100, 'currency_symbol' => 'kr', 'currency_code' => 'ISK', 'code' => 'IS','name' => "Iceland",'phonecode' => 354),
            array('id' => 101, 'currency_symbol' => '₹', 'currency_code' => 'INR', 'code' => 'IN','name' => "India",'phonecode' => 91),
            array('id' => 102, 'currency_symbol' => 'Rp', 'currency_code' => 'IDR', 'code' => 'ID','name' => "Indonesia",'phonecode' => 62),
            array('id' => 103, 'currency_symbol' => '﷼', 'currency_code' => 'IRR', 'code' => 'IR','name' => "Iran",'phonecode' => 98),
            array('id' => 104, 'currency_symbol' => 'ع.د', 'currency_code' => 'IQD', 'code' => 'IQ','name' => "Iraq",'phonecode' => 964),
            array('id' => 105, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'IE','name' => "Ireland",'phonecode' => 353),
            array('id' => 106, 'currency_symbol' => '₪', 'currency_code' => 'ILS', 'code' => 'IL','name' => "Israel",'phonecode' => 972),
            array('id' => 107, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'IT','name' => "Italy",'phonecode' => 39),
            array('id' => 108, 'currency_symbol' => 'J$', 'currency_code' => 'JMD', 'code' => 'JM','name' => "Jamaica",'phonecode' => 1876),
            array('id' => 109, 'currency_symbol' => '¥', 'currency_code' => 'JPY', 'code' => 'JP','name' => "Japan",'phonecode' => 81),
            array('id' => 110, 'currency_symbol' => '£', 'currency_code' => 'GBP', 'code' => 'XJ','name' => "Jersey",'phonecode' => 44),
            array('id' => 111, 'currency_symbol' => 'د.ا', 'currency_code' => 'JOD', 'code' => 'JO','name' => "Jordan",'phonecode' => 962),
            array('id' => 112, 'currency_symbol' => 'лв', 'currency_code' => 'KZT', 'code' => 'KZ','name' => "Kazakhstan",'phonecode' => 7),
            array('id' => 113, 'currency_symbol' => 'Sh', 'currency_code' => 'KES', 'code' => 'KE','name' => "Kenya",'phonecode' => 254),
            array('id' => 114, 'currency_symbol' => '$', 'currency_code' => 'AUD', 'code' => 'KI','name' => "Kiribati",'phonecode' => 686),
            array('id' => 115, 'currency_symbol' => '₩', 'currency_code' => 'KPW', 'code' => 'KP','name' => "Korea North",'phonecode' => 850),
            array('id' => 116, 'currency_symbol' => '₩', 'currency_code' => 'KRW', 'code' => 'KR','name' => "Korea South",'phonecode' => 82),
            array('id' => 117, 'currency_symbol' => 'د.ك', 'currency_code' => 'KWD', 'code' => 'KW','name' => "Kuwait",'phonecode' => 965),
            array('id' => 118, 'currency_symbol' => 'лв', 'currency_code' => 'KGS', 'code' => 'KG','name' => "Kyrgyzstan",'phonecode' => 996),
            array('id' => 119, 'currency_symbol' => '₭', 'currency_code' => 'LAK', 'code' => 'LA','name' => "Laos",'phonecode' => 856),
            array('id' => 120, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'LV','name' => "Latvia",'phonecode' => 371),
            array('id' => 121, 'currency_symbol' => '£', 'currency_code' => 'LBP', 'code' => 'LB','name' => "Lebanon",'phonecode' => 961),
            array('id' => 122, 'currency_symbol' => 'R', 'currency_code' => 'ZAR', 'code' => 'LS','name' => "Lesotho",'phonecode' => 266),
            array('id' => 123, 'currency_symbol' => '$', 'currency_code' => 'LRD', 'code' => 'LR','name' => "Liberia",'phonecode' => 231),
            array('id' => 124, 'currency_symbol' => 'ل.د', 'currency_code' => 'LYD', 'code' => 'LY','name' => "Libya",'phonecode' => 218),
            array('id' => 125, 'currency_symbol' => 'CHF', 'currency_code' => 'CHF', 'code' => 'LI','name' => "Liechtenstein",'phonecode' => 423),
            array('id' => 126, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'LT','name' => "Lithuania",'phonecode' => 370),
            array('id' => 127, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'LU','name' => "Luxembourg",'phonecode' => 352),
            array('id' => 128, 'currency_symbol' => 'P', 'currency_code' => 'MOP', 'code' => 'MO','name' => "Macau S.A.R.",'phonecode' => 853),
            array('id' => 129, 'currency_symbol' => 'ден', 'currency_code' => 'MKD', 'code' => 'MK','name' => "Macedonia",'phonecode' => 389),
            array('id' => 130, 'currency_symbol' => 'Ar', 'currency_code' => 'MGA', 'code' => 'MG','name' => "Madagascar",'phonecode' => 261),
            array('id' => 131, 'currency_symbol' => 'MK', 'currency_code' => 'MWK', 'code' => 'MW','name' => "Malawi",'phonecode' => 265),
            array('id' => 132, 'currency_symbol' => 'RM', 'currency_code' => 'MYR', 'code' => 'MY','name' => "Malaysia",'phonecode' => 60),
            array('id' => 133, 'currency_symbol' => 'ރ.', 'currency_code' => 'MVR', 'code' => 'MV','name' => "Maldives",'phonecode' => 960),
            array('id' => 134, 'currency_symbol' => 'CFA', 'currency_code' => 'XOF', 'code' => 'ML','name' => "Mali",'phonecode' => 223),
            array('id' => 135, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'MT','name' => "Malta",'phonecode' => 356),
            array('id' => 136, 'currency_symbol' => '£', 'currency_code' => 'GBP', 'code' => 'XM','name' => "Man (Isle of)",'phonecode' => 44),
            array('id' => 137, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'MH','name' => "Marshall Islands",'phonecode' => 692),
            array('id' => 138, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'MQ','name' => "Martinique",'phonecode' => 596),
            array('id' => 139, 'currency_symbol' => 'UM', 'currency_code' => 'MRU', 'code' => 'MR','name' => "Mauritania",'phonecode' => 222),
            array('id' => 140, 'currency_symbol' => '₨', 'currency_code' => 'MUR', 'code' => 'MU','name' => "Mauritius",'phonecode' => 230),
            array('id' => 141, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'YT','name' => "Mayotte",'phonecode' => 269),
            array('id' => 142, 'currency_symbol' => '$', 'currency_code' => 'MXN', 'code' => 'MX','name' => "Mexico",'phonecode' => 52),
            array('id' => 143, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'FM','name' => "Micronesia",'phonecode' => 691),
            array('id' => 144, 'currency_symbol' => 'L', 'currency_code' => 'MDL', 'code' => 'MD','name' => "Moldova",'phonecode' => 373),
            array('id' => 145, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'MC','name' => "Monaco",'phonecode' => 377),
            array('id' => 146, 'currency_symbol' => '₮', 'currency_code' => 'MNT', 'code' => 'MN','name' => "Mongolia",'phonecode' => 976),
            array('id' => 147, 'currency_symbol' => '$', 'currency_code' => 'XCD', 'code' => 'MS','name' => "Montserrat",'phonecode' => 1664),
            array('id' => 148, 'currency_symbol' => 'د.م.', 'currency_code' => 'MAD', 'code' => 'MA','name' => "Morocco",'phonecode' => 212),
            array('id' => 149, 'currency_symbol' => 'MT', 'currency_code' => 'MZN', 'code' => 'MZ','name' => "Mozambique",'phonecode' => 258),
            array('id' => 150, 'currency_symbol' => 'K', 'currency_code' => 'MMK', 'code' => 'MM','name' => "Myanmar",'phonecode' => 95),
            array('id' => 151, 'currency_symbol' => 'R', 'currency_code' => 'ZAR', 'code' => 'NA','name' => "Namibia",'phonecode' => 264),
            array('id' => 152, 'currency_symbol' => '$', 'currency_code' => 'AUD', 'code' => 'NR','name' => "Nauru",'phonecode' => 674),
            array('id' => 153, 'currency_symbol' => '₨', 'currency_code' => 'NPR', 'code' => 'NP','name' => "Nepal",'phonecode' => 977),
            array('id' => 154, 'currency_symbol' => 'ƒ', 'currency_code' => 'ANG', 'code' => 'AN','name' => "Netherlands Antilles",'phonecode' => 599),
            array('id' => 155, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'NL','name' => "Netherlands The",'phonecode' => 31),
            array('id' => 156, 'currency_symbol' => '₣', 'currency_code' => 'XPF', 'code' => 'NC','name' => "New Caledonia",'phonecode' => 687),
            array('id' => 157, 'currency_symbol' => '$', 'currency_code' => 'NZD', 'code' => 'NZ','name' => "New Zealand",'phonecode' => 64),
            array('id' => 158, 'currency_symbol' => 'C$', 'currency_code' => 'NIO', 'code' => 'NI','name' => "Nicaragua",'phonecode' => 505),
            array('id' => 159, 'currency_symbol' => 'CFA', 'currency_code' => 'XOF', 'code' => 'NE','name' => "Niger",'phonecode' => 227),
            array('id' => 160, 'currency_symbol' => '₦', 'currency_code' => 'NGN', 'code' => 'NG','name' => "Nigeria",'phonecode' => 234),
            array('id' => 161, 'currency_symbol' => '$', 'currency_code' => 'NZD', 'code' => 'NU','name' => "Niue",'phonecode' => 683),
            array('id' => 162, 'currency_symbol' => '$', 'currency_code' => 'AUD', 'code' => 'NF','name' => "Norfolk Island",'phonecode' => 672),
            array('id' => 163, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'MP','name' => "Northern Mariana Islands",'phonecode' => 1670),
            array('id' => 164, 'currency_symbol' => 'kr', 'currency_code' => 'NOK', 'code' => 'NO','name' => "Norway",'phonecode' => 47),
            array('id' => 165, 'currency_symbol' => '﷼', 'currency_code' => 'OMR', 'code' => 'OM','name' => "Oman",'phonecode' => 968),
            array('id' => 166, 'currency_symbol' => '₨', 'currency_code' => 'PKR', 'code' => 'PK','name' => "Pakistan",'phonecode' => 92),
            array('id' => 167, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'PW','name' => "Palau",'phonecode' => 680),
            array('id' => 168, 'currency_symbol' => '', 'currency_code' => '', 'code' => 'PS','name' => "Palestinian Territory Occupied",'phonecode' => 970),
            array('id' => 169, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'PA','name' => "Panama",'phonecode' => 507),
            array('id' => 170, 'currency_symbol' => 'K', 'currency_code' => 'PGK', 'code' => 'PG','name' => "Papua new Guinea",'phonecode' => 675),
            array('id' => 171, 'currency_symbol' => 'Gs', 'currency_code' => 'PYG', 'code' => 'PY','name' => "Paraguay",'phonecode' => 595),
            array('id' => 172, 'currency_symbol' => 'S/.', 'currency_code' => 'PEN', 'code' => 'PE','name' => "Peru",'phonecode' => 51),
            array('id' => 173, 'currency_symbol' => 'Php', 'currency_code' => 'PHP', 'code' => 'PH','name' => "Philippines",'phonecode' => 63),
            array('id' => 174, 'currency_symbol' => '$', 'currency_code' => 'NZD', 'code' => 'PN','name' => "Pitcairn Island",'phonecode' => 0),
            array('id' => 175, 'currency_symbol' => 'zł', 'currency_code' => 'PLN', 'code' => 'PL','name' => "Poland",'phonecode' => 48),
            array('id' => 176, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'PT','name' => "Portugal",'phonecode' => 351),
            array('id' => 177, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'PR','name' => "Puerto Rico",'phonecode' => 1787),
            array('id' => 178, 'currency_symbol' => '﷼', 'currency_code' => 'QAR', 'code' => 'QA','name' => "Qatar",'phonecode' => 974),
            array('id' => 179, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'RE','name' => "Reunion",'phonecode' => 262),
            array('id' => 180, 'currency_symbol' => 'lei', 'currency_code' => 'RON', 'code' => 'RO','name' => "Romania",'phonecode' => 40),
            array('id' => 181, 'currency_symbol' => 'руб', 'currency_code' => 'RUB', 'code' => 'RU','name' => "Russia",'phonecode' => 70),
            array('id' => 182, 'currency_symbol' => '₣', 'currency_code' => 'RWF', 'code' => 'RW','name' => "Rwanda",'phonecode' => 250),
            array('id' => 183, 'currency_symbol' => '£', 'currency_code' => 'SHP', 'code' => 'SH','name' => "Saint Helena",'phonecode' => 290),
            array('id' => 184, 'currency_symbol' => '$', 'currency_code' => 'XCD', 'code' => 'KN','name' => "Saint Kitts And Nevis",'phonecode' => 1869),
            array('id' => 185, 'currency_symbol' => '$', 'currency_code' => 'XCD', 'code' => 'LC','name' => "Saint Lucia",'phonecode' => 1758),
            array('id' => 186, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'PM','name' => "Saint Pierre and Miquelon",'phonecode' => 508),
            array('id' => 187, 'currency_symbol' => '$', 'currency_code' => 'XCD', 'code' => 'VC','name' => "Saint Vincent And The Grenadines",'phonecode' => 1784),
            array('id' => 188, 'currency_symbol' => 'T', 'currency_code' => 'WST', 'code' => 'WS','name' => "Samoa",'phonecode' => 684),
            array('id' => 189, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'SM','name' => "San Marino",'phonecode' => 378),
            array('id' => 190, 'currency_symbol' => 'Db', 'currency_code' => 'STN', 'code' => 'ST','name' => "Sao Tome and Principe",'phonecode' => 239),
            array('id' => 191, 'currency_symbol' => '﷼', 'currency_code' => 'SAR', 'code' => 'SA','name' => "Saudi Arabia",'phonecode' => 966),
            array('id' => 192, 'currency_symbol' => 'CFA', 'currency_code' => 'XOF', 'code' => 'SN','name' => "Senegal",'phonecode' => 221),
            array('id' => 193, 'currency_symbol' => 'Дин', 'currency_code' => 'RSD', 'code' => 'RS','name' => "Serbia",'phonecode' => 381),
            array('id' => 194, 'currency_symbol' => '₨', 'currency_code' => 'SCR', 'code' => 'SC','name' => "Seychelles",'phonecode' => 248),
            array('id' => 195, 'currency_symbol' => 'Le', 'currency_code' => 'SLL', 'code' => 'SL','name' => "Sierra Leone",'phonecode' => 232),
            array('id' => 196, 'currency_symbol' => '$', 'currency_code' => 'SGD', 'code' => 'SG','name' => "Singapore",'phonecode' => 65),
            array('id' => 197, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'SK','name' => "Slovakia",'phonecode' => 421),
            array('id' => 198, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'SI','name' => "Slovenia",'phonecode' => 386),
            array('id' => 199, 'currency_symbol' => '£', 'currency_code' => 'GBP', 'code' => 'XG','name' => "Smaller Territories of the UK",'phonecode' => 44),
            array('id' => 200, 'currency_symbol' => '$', 'currency_code' => 'SBD', 'code' => 'SB','name' => "Solomon Islands",'phonecode' => 677),
            array('id' => 201, 'currency_symbol' => 'S', 'currency_code' => 'SOS', 'code' => 'SO','name' => "Somalia",'phonecode' => 252),
            array('id' => 202, 'currency_symbol' => 'R', 'currency_code' => 'ZAR', 'code' => 'ZA','name' => "South Africa",'phonecode' => 27),
            array('id' => 203, 'currency_symbol' => '', 'currency_code' => '', 'code' => 'GS','name' => "South Georgia",'phonecode' => 0),
            array('id' => 204, 'currency_symbol' => '£', 'currency_code' => 'SSP', 'code' => 'SS','name' => "South Sudan",'phonecode' => 211),
            array('id' => 205, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'ES','name' => "Spain",'phonecode' => 34),
            array('id' => 206, 'currency_symbol' => '₨', 'currency_code' => 'LKR', 'code' => 'LK','name' => "Sri Lanka",'phonecode' => 94),
            array('id' => 207, 'currency_symbol' => '£', 'currency_code' => 'SDG', 'code' => 'SD','name' => "Sudan",'phonecode' => 249),
            array('id' => 208, 'currency_symbol' => '$', 'currency_code' => 'SRD', 'code' => 'SR','name' => "Suriname",'phonecode' => 597),
            array('id' => 209, 'currency_symbol' => 'kr', 'currency_code' => 'NOK', 'code' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'phonecode' => 47),
            array('id' => 210, 'currency_symbol' => 'L', 'currency_code' => 'SZL', 'code' => 'SZ','name' => "Swaziland",'phonecode' => 268),
            array('id' => 211, 'currency_symbol' => 'kr', 'currency_code' => 'SEK', 'code' => 'SE','name' => "Sweden",'phonecode' => 46),
            array('id' => 212, 'currency_symbol' => 'CHF', 'currency_code' => 'CHF', 'code' => 'CH','name' => "Switzerland",'phonecode' => 41),
            array('id' => 213, 'currency_symbol' => '£', 'currency_code' => 'SYP', 'code' => 'SY','name' => "Syria",'phonecode' => 963),
            array('id' => 214, 'currency_symbol' => 'NT$', 'currency_code' => 'TWD', 'code' => 'TW','name' => "Taiwan",'phonecode' => 886),
            array('id' => 215, 'currency_symbol' => 'ЅМ', 'currency_code' => 'TJS', 'code' => 'TJ','name' => "Tajikistan",'phonecode' => 992),
            array('id' => 216, 'currency_symbol' => 'sh', 'currency_code' => 'TZS', 'code' => 'TZ','name' => "Tanzania",'phonecode' => 255),
            array('id' => 217, 'currency_symbol' => '฿', 'currency_code' => 'THB', 'code' => 'TH','name' => "Thailand",'phonecode' => 66),
            array('id' => 218, 'currency_symbol' => 'CFA', 'currency_code' => 'XOF', 'code' => 'TG','name' => "Togo",'phonecode' => 228),
            array('id' => 219, 'currency_symbol' => '$', 'currency_code' => 'NZD', 'code' => 'TK','name' => "Tokelau",'phonecode' => 690),
            array('id' => 220, 'currency_symbol' => 'T$', 'currency_code' => 'TOP', 'code' => 'TO','name' => "Tonga",'phonecode' => 676),
            array('id' => 221, 'currency_symbol' => 'TT$', 'currency_code' => 'TTD', 'code' => 'TT','name' => "Trinidad And Tobago",'phonecode' => 1868),
            array('id' => 222, 'currency_symbol' => 'د.ت', 'currency_code' => 'TND', 'code' => 'TN','name' => "Tunisia",'phonecode' => 216),
            array('id' => 223, 'currency_symbol' => '₺', 'currency_code' => 'TRY', 'code' => 'TR','name' => "Turkey",'phonecode' => 90),
            array('id' => 224, 'currency_symbol' => 'm', 'currency_code' => 'TMT', 'code' => 'TM','name' => "Turkmenistan",'phonecode' => 7370),
            array('id' => 225, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'TC','name' => "Turks And Caicos Islands",'phonecode' => 1649),
            array('id' => 226, 'currency_symbol' => '$', 'currency_code' => 'AUD', 'code' => 'TV','name' => "Tuvalu",'phonecode' => 688),
            array('id' => 227, 'currency_symbol' => 'Sh', 'currency_code' => 'UGX', 'code' => 'UG','name' => "Uganda",'phonecode' => 256),
            array('id' => 228, 'currency_symbol' => '₴', 'currency_code' => 'UAH', 'code' => 'UA','name' => "Ukraine",'phonecode' => 380),
            array('id' => 229, 'currency_symbol' => 'د.إ', 'currency_code' => 'AED', 'code' => 'AE','name' => "United Arab Emirates",'phonecode' => 971),
            array('id' => 230, 'currency_symbol' => '£', 'currency_code' => 'GBP', 'code' => 'GB','name' => "United Kingdom",'phonecode' => 44),
            array('id' => 231, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'US','name' => "United States",'phonecode' => 1),
            array('id' => 232, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'UM','name' => "United States Minor Outlying Islands",'phonecode' => 1),
            array('id' => 233, 'currency_symbol' => '$U', 'currency_code' => 'UYU', 'code' => 'UY','name' => "Uruguay",'phonecode' => 598),
            array('id' => 234, 'currency_symbol' => 'лв', 'currency_code' => 'UZS', 'code' => 'UZ','name' => "Uzbekistan",'phonecode' => 998),
            array('id' => 235, 'currency_symbol' => 'Vt', 'currency_code' => 'VUV', 'code' => 'VU','name' => "Vanuatu",'phonecode' => 678),
            array('id' => 236, 'currency_symbol' => '€', 'currency_code' => 'EUR', 'code' => 'VA','name' => "Vatican City State (Holy See)",'phonecode' => 39),
            array('id' => 237, 'currency_symbol' => 'Bs', 'currency_code' => 'VEF', 'code' => 'VE','name' => "Venezuela",'phonecode' => 58),
            array('id' => 238, 'currency_symbol' => '₫', 'currency_code' => 'VND', 'code' => 'VN','name' => "Vietnam",'phonecode' => 84),
            array('id' => 239, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'VG','name' => "Virgin Islands (British)",'phonecode' => 1284),
            array('id' => 240, 'currency_symbol' => '$', 'currency_code' => 'USD', 'code' => 'VI','name' => "Virgin Islands (US)",'phonecode' => 1340),
            array('id' => 241, 'currency_symbol' => '₣', 'currency_code' => 'XPF', 'code' => 'WF','name' => "Wallis And Futuna Islands",'phonecode' => 681),
            array('id' => 242, 'currency_symbol' => 'د.م.', 'currency_code' => 'MAD', 'code' => 'EH','name' => "Western Sahara",'phonecode' => 212),
            array('id' => 243, 'currency_symbol' => '﷼', 'currency_code' => 'YER', 'code' => 'YE','name' => "Yemen",'phonecode' => 967),
            array('id' => 244, 'currency_symbol' => '', 'currency_code' => '', 'code' => 'YU','name' => "Yugoslavia",'phonecode' => 38),
            array('id' => 245, 'currency_symbol' => 'ZK', 'currency_code' => 'ZMW', 'code' => 'ZM','name' => "Zambia",'phonecode' => 260),
            array('id' => 246, 'currency_symbol' => 'Z$', 'currency_code' => 'ZWD', 'code' => 'ZW','name' => "Zimbabwe",'phonecode' => 263),
            );
            DB::table('countries')->insert($countries);
    }
}
